### ISSUE TITLE
Missing Columns

### ISSUE THREAD

**Issue by magnusol9** [TakahiroShimada/SDLfilter#3]
Hello
I am trying to use the package, but I keep getting the same error messages when trying to apply any filter other than dup. I have attached a dataset and a script that illustrates my problem better.
[animals.csv](https://github.com/TakahiroShimada/SDLfilter/files/9451999/animals.csv)

#Load Packages
library(tidyverse)
library(dplyr)
library(SDLfilter)
library(lubridate)

#Load dataset
#This is dataset was created by taking the DateTime from one sample and the coordinates from another
animals <- read.csv('data/animals.csv')

#Lubridate 'DateTime'
animals <- animals %>%
  mutate(DateTime = mdy_hm(DateTime))

#Remove temporal and spatial duplicates
animals.dup <- animals %>%
  dupfilter()

#Calculate the maximum linear speed betwee two consecutive locations
V <- animals.dup %>% 
  vmax()

#When I try to execute this function I just recieve this error message
    #dupfilter_exact removed 0 of 0 locations
    #dupfilter_qi removed 0 of 0 locations
    #Error in qi[qi %in% "A"] <- "-1" : object 'qi' not found
    #In addition: Warning messages:
       #1: Unknown or uninitialised column: `pTime`. 
       #2: Unknown or uninitialised column: `qi`. 
       #3: Unknown or uninitialised column: `pQI`. 
       #4: Unknown or uninitialised column: `sTime`. 
       #5: Unknown or uninitialised column: `qi`. 
       #6: Unknown or uninitialised column: `sQI`. 
       #7: Unknown or uninitialised column: `qi`. 

#Calculate the maximum one-way linear speed of a loop trip
VLP <- animals.dup %>%
  vmaxlp()

#I get the same error as above when I try to run this function. 

## Run ddfilter
turtle.dd <- ddfilter(animals.dup, vmax=V, vmaxlp=VLP)

**Comment by TakahiroShimada** [comment]
Hi thanks for posting the issue. 
You are getting the error because the 'qi' argument is set to default (i.e. 5 for vmaxlp and 4 vmax) but your data do not contain locations that are associated with 5 or greater qi values. One way to get around is to use a reliable qi value. Assuming your data is Argos locations, that may be 1. 

Using your sample data, vmax ran using qi = 1 but vmaxlp didn't since no 'loop trip' was found within the dataset. Other option to use the ddfilter function would be to estimate vmax and vmaxlp from other studies if they exist.

On the other note, I added a maximum likelihood approach to estimate vmax and vmaxlp. If this is of your interest, you can get the development version of the package from the Github page and select method = 'ML' when you run the vmax and vmaxlp functions. 

Hope this will solve the issue.
